# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3f822bdea4a6af6326210122283351a1"
name = "Discount Ladder"
handle = "discount-ladder"
application_url = "https://discount-ladder--development.gadget.app/api/shopify/install-or-render"
embedded = true

[build]
dev_store_url = "jv-studio-sandbox.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://discount-ladder--development.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "https://discount-ladder--development.gadget.app/api/webhooks/shopify"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false
