# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4d42bfa80c8129312e48512e6d8e45bc"
name = "Discount Ladder Staging"
handle = "discount-ladder-staginng"
application_url = "https://discount-ladder--test.gadget.app/api/shopify/install-or-render"
embedded = true

[build]
dev_store_url = "jvdevstaging.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://discount-ladder--test.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
